syntax on
color torte
set guifont=Consolas:h11 # Source_Code
set nu ts=4 sw=4 sts=4 et ai si cin hls ru t_Co=256
set mouse=a bs=2 ci nocp ar fencs=utf-8
set sm mat=0
filetype plugin indent on
imap {<CR>  {<CR>}<Esc>O
nmap <C-Up> <Up>ddp<Up>
nmap <C-Down> ddp

map <F9> :!run %:r<CR>
map <F10> :e %:r.cpp<CR>
map <F11> :e %:r.in<CR>